theme: jekyll-theme-minimal
title: Aman Katyal's Engineering Portfolio
description: This portfolio is a curated collection of projects and technical experiences demonstrating expertise in full-stack hardware and firmware development, from initial schematic capture in KiCad to low-level microcontroller programming in Embedded C/C++
