theme: jekyll-theme-cayman
title: Aman Katyal | Portfolio
author: Aman Katyal
email: itsamankatyal@gmail.com
description: Computer Engineering Student at Purdue University specializing in Hardware Design, UVM Verification, and Embedded Systems.
show_downloads: false
url: "https://aman-katyal.github.io"